### ISSUE TITLE
Create method to change showLog at runtime

### ISSUE THREAD

**Issue by DavideCarvalho** [thecreazy/common-loggo#3]
Would be nice if we could add the possilibity to log or not to log at runtime

**Comment by thecreazy** [comment]
It's a very simple feature to add, but do you think it's really necessary? how many times do you not know whether or not you need to view logs in that context?

**Comment by DavideCarvalho** [comment]
I think is just one more thing that will help people when they need it. I can't think is a use case right now, but if it's so simple, why not?
Maybe a use case is testing application in staging mode and if something goes wrong, you can just turn on the logs without making another deploy.

**Comment by thecreazy** [comment]
Done in versione `1.1.0`
